language: python

matrix:
  include:
    - os: linux
      python: 3.5

install:
  - "lsb_release -a"
  - "sudo apt-get install -y  build-essential  git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev"
  - "pip install --upgrade pip virtualenv setuptools"
  - "pip install Cython"
  - "pip install pygments docutils"
  - "pip install git+https://github.com/kivy/kivy.git@master"
  - "python -m PyInstaller reversi.spec"
