language: python

matrix:
  include:
    - os: linux
      python: 3.5
      dist: trusty
      sudo: required
    - os: osx
      language: generic

install:
  #Print system info
  - uname -a

  #Run install scripts per system
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then bash build-scripts/install-mac.sh; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then bash build-scripts/install-linux.sh; fi

  #Build executable files
  - python3 -m PyInstaller reversi.spec

#Run tests
script: pytest
