language: python

matrix:
  include:
    - os: linux
      python: 3.5
      dist: trusty
      sudo: required
    - os: osx
      language: generic
      env: PYTHON=3.5.3

install:
  #Print system info
  - uname -a

  #Run install scripts per system
  - chmod +x build-scripts/install-mac-sh
  - chmod +x build-scripts/install-linux.sh
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then ./build-scripts/install-mac.sh; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then ./build-scripts/install-linux.sh; fi
  - ls -la dist/reversi

#Run tests
script: python -m pytest
