language: python

# see https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      python: 3.4
    - os: osx
      python: 3.4

install:
  - "pip install -r requirements.txt"
  - "python -m PyInstaller reversi.spec"