language: python

matrix:
  include:
#    - os: linux
#      python: 3.5
#      dist: trusty
#      sudo: required
    - os: osx
      language: generic
      env: PYTHON=3.5.3

install:
  # Print system info
  - uname -a

  # Update brew packages on macOS
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi

  # Install dependencies per system
  - chmod +x ci/linux/*
  - chmod +x ci/mac/*

  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then source ./ci/mac/install.sh; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then source ./ci/linux/install.sh; fi

script:
  - python -m pytest
  # Build executables
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then ./ci/mac/build.sh; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then ./ci/linux/build.sh; fi